<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260129091905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE panier ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE panier ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE panier ALTER date_ajout DROP DEFAULT');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF2FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF2567F5183 FOREIGN KEY (film_id) REFERENCES film (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_24CC0DF2FB88E14F ON panier (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_24CC0DF2567F5183 ON panier (film_id)');
        $this->addSql('ALTER TABLE promotion ALTER tauxpromo TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE promotion ADD CONSTRAINT FK_C11D7DD19D82865 FOREIGN KEY (idjour) REFERENCES jours (idjour) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE panier DROP CONSTRAINT FK_24CC0DF2FB88E14F');
        $this->addSql('ALTER TABLE panier DROP CONSTRAINT FK_24CC0DF2567F5183');
        $this->addSql('DROP INDEX IDX_24CC0DF2FB88E14F');
        $this->addSql('DROP INDEX IDX_24CC0DF2567F5183');
        $this->addSql('ALTER TABLE panier ALTER id SET DEFAULT nextval(\'panier_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE panier ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE panier ALTER date_ajout SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE promotion DROP CONSTRAINT FK_C11D7DD19D82865');
        $this->addSql('ALTER TABLE promotion ALTER tauxpromo TYPE NUMERIC(5, 2)');
    }
}
